#  Feishu 飞书
APP_ID: cli_xxx
APP_SECRET: xxx
APP_ENCRYPT_KEY: xxx
APP_VERIFICATION_TOKEN: xxx
# 请确保和飞书应用管理平台中的设置一致
BOT_NAME: xxx
# openAI key 支持负载均衡 可以填写多个key 用逗号分隔
OPENAI_KEY: sk-xxx,sk-xxx,sk-xxx

# 服务器配置
HTTP_PORT: 9000
HTTPS_PORT: 9001

# Prompt
DEFAULT_PROMPT: "You are an AI assistant that helps people find information. You answer should be concise and accurate"
PROMPT_DESCRIPTION_LIST:
  - "无情的AI翻译"
  - "无情的Json格式化机器"
  - "赛博朋友"
PROMPT_VALUE_LIST:
  - "You are an AI assistant that helps people translate between English and Chinese.
     If I only give you one word in English, you first translate, and in the nextline you shoule explain the world using Chinese detailly.
     Do not do any other things, just translate the word."
  - "You need to help me format the json string. I will give you a json string and you need to format it and return it to me. Do not do any other things, just format the json string."
  - "I want you to act as my friend. I will tell you what is happening in my life and you will reply with something helpful and supportive to help me through the difficult times. Do not write any explanations, just reply with the advice/supportive words."

# OpenAI 配置

# openai 地址, 一般不需要修改, 除非你有自己的反向代理
API_URL: https://api.openai.com
# 访问OpenAI的代理设置, 例如 "http://127.0.0.1:7890", ""代表不使用代理
HTTP_PROXY: ""

# Azure 配置
IS_AZURE: true
AZURE_API_HOST: https://xxx.openai.azure.com/
AZURE_API_KEY: xxx
GPT_MODEL: gpt-35-turbo

